### ISSUE TITLE
Front-end for settings page

### ISSUE THREAD

**Issue by ChristienGuy** [eclectic-matt/wordpress#2]
I figure essentially just a list of inputs pre-populated with whatever items already exist (basically what you have already)

Then a little js for dynamically adding new ones. 

Then just workout how to get submit to talk to WP backed and store items in DB somewhere (for reference in the actual post page)

**Comment by ChristienGuy** [comment]
PR: https://github.com/eclectic-matt/wordpress/pull/4

Begins this work, does not store anything currently but will allow adding and editing items.

**Comment by eclectic-matt** [comment]
Implemented now as part of last night's update, and the array of input values (checklist-item) is now stored via update_option to the DB

**Comment by ChristienGuy** [comment]
Completed basic front-end. Will work on feature/issues as separate tickets.
